In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize

---
# &diams;  Matrix scaling/normalization

**Task-1**: Create the following 5x4 numpy array, and save it as `x`.
```
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]
 [0. 0. 5. 0.]]
 ```

In [2]:
# ANSWER

x = [[1.0, 0.0, 0.0, 0.0],
     [0.0, 2.0, 0.0, 0.0],
     [0.0, 0.0, 3.0, 0.0],
     [0.0, 0.0, 0.0, 4.0],
     [0.0, 0.0, 5.0, 0.0]]


x = np.array(x)
x

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.],
       [0., 0., 5., 0.]])

---
**Task-2**: Scale the matrix by row, so that all rows have mean 0 and standard deviation 1. Save the scaled matrix as `x_scaled`.

The expected result is 
```
[[ 1.73205081 -0.57735027 -0.57735027 -0.57735027]
 [-0.57735027  1.73205081 -0.57735027 -0.57735027]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027]
 [-0.57735027 -0.57735027 -0.57735027  1.73205081]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027]]
 ```

In [3]:
# ANSWER
import numpy as np

#Define the matrix
x = np.array([[1., 0., 0., 0.],
              [0., 2., 0., 0.],
              [0., 0., 3., 0.],
              [0., 0., 0., 4.],
              [0., 0., 5., 0.]])

# Compute mean and standard deviation of each row
row_mean = np.mean(x, axis=1, keepdims=True)
row_stdev = np.std(x, axis=1, keepdims=True)

# subtract the row means and divide by the row standard deviations
x_scaled = (x -row_mean) / row_stdev

# diplay value
print(x_scaled)


[[ 1.73205081 -0.57735027 -0.57735027 -0.57735027]
 [-0.57735027  1.73205081 -0.57735027 -0.57735027]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027]
 [-0.57735027 -0.57735027 -0.57735027  1.73205081]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027]]


In [4]:
#testing the mean and standard deviation of each row in a numpy array 
print(np.around(x_scaled.mean(axis=1)))
print(x_scaled.std(axis=1))

[-0. -0.  0. -0.  0.]
[1. 1. 1. 1. 1.]


---
**Task-3**: Scale the matrix by column, so that all columns have mean 0 and standard deviation 1. Save the scaled matrix as `x_scaled2`.


The expected result is 
```
[[ 2.         -0.5        -0.77702869 -0.5       ]
 [-0.5         2.         -0.77702869 -0.5       ]
 [-0.5        -0.5         0.6799001  -0.5       ]
 [-0.5        -0.5        -0.77702869  2.        ]
 [-0.5        -0.5         1.65118597 -0.5       ]]
 ```

In [5]:
#ANSWER
import numpy as np

# Repeating all the steps again
# Define the matrix
x = np.array([[1., 0., 0., 0.],
              [0., 2., 0., 0.],
              [0., 0., 3., 0.],
              [0., 0., 0., 4.],
              [0., 0., 5., 0.]])

# Compute the mean and standard deviation of each column
col_mean = np.mean(x, axis=0, keepdims=True)
col_stdev = np.std(x, axis=0, keepdims=True)

# subtract the column mean and then divide by the standard deviations
x_scaled2 = (x - col_mean)/ col_stdev

print(x_scaled2)


[[ 2.         -0.5        -0.77702869 -0.5       ]
 [-0.5         2.         -0.77702869 -0.5       ]
 [-0.5        -0.5         0.6799001  -0.5       ]
 [-0.5        -0.5        -0.77702869  2.        ]
 [-0.5        -0.5         1.65118597 -0.5       ]]


In [6]:
# testing
print(np.around(x_scaled2.mean(axis=0)))
print(x_scaled2.std(axis=0))

[-0. -0. -0.  0.]
[1. 1. 1. 1.]
