---
# Numpy Arrays

- Creat a numpy array from a python list

- Create a numpy array with initializing functions
    * `np.zeros()`
    * `np.ones()`
    * `np.arange()`

- Change the shape of an exisitng numpy array
    * `np.reshape()`



In [1]:
import numpy as np 

a_1d = np.arange(3)
print(a_1d)
print("----")

a_2d = np.array([[1.,2.], [3.,4.]])
print(a_2d)
print("----")

a_3d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a_3d)

[0 1 2]
----
[[1. 2.]
 [3. 4.]]
----
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
np.zeros(5)  #creating an array of five zeros 

array([0., 0., 0., 0., 0.])

In [3]:
np.ones((5,5)) * 2023 #creating 2-D array of 2023s

array([[2023., 2023., 2023., 2023., 2023.],
       [2023., 2023., 2023., 2023., 2023.],
       [2023., 2023., 2023., 2023., 2023.],
       [2023., 2023., 2023., 2023., 2023.],
       [2023., 2023., 2023., 2023., 2023.]])

In [4]:
#creating aaray of four even numbers starting from 2, arranged in 2x2 array 
np.arange(2, 10, 2)
np.arange(2, 10, 2).reshape(-1, 2)

array([[2, 4],
       [6, 8]])

---
# Array Broadcasting

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

1. they are equal, or
2. one of them is 1 (or missing)

![](http://scipy-lectures.org/_images/numpy_broadcasting.png)

In [5]:
import numpy as np

*Illustration of Array addition in python*

In [6]:
A = np.tile(np.arange(0, 40, 10), (3, 1)).T
A

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [7]:
B = np.tile(np.arange(3), (4, 1))
B

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
A + B

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [9]:
b = np.arange(3)
b

array([0, 1, 2])

In [10]:
A + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [11]:
a = np.arange(0, 40, 10).reshape(-1, 1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [12]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

---
### &diams; Exercise

Create a (3,4) numpy array $A$ such that $A_{ij} = i\times j$.

1. Use list comprehension
2. Use array broadcasting

The resulting array is,
```
array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6]])
```


In [13]:
# 1. Use list comprehension 
import numpy as np

np.array([[i * j for j in range(4)] for i in range(3)])


array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6]])

In [14]:
# 2. Use array broadcasting
x=np.zeros((3,4))
x[1,1:]=np.arange(1,4,1)
x[2,1:]=np.arange(2,8,2)
x

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

---
# Array indexing and slicing

![](http://scipy-lectures.org/_images/numpy_indexing.png)



In [15]:
a = 10*np.arange(6).reshape(-1,1) + np.arange(6)
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [16]:
# red-color selection
a[0, 3:5]

array([3, 4])

In [17]:
# green-color selection
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [18]:
# blue-color selection
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [19]:
# purple-color selection
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

---
### &diams; Exercise
Create the following matrices

```
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])
```

In [20]:
import numpy as np

A = np.ones((6,6))
A[1:-1,2:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


```
array([[   0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.],
       [   0., 2023., 2022., 2021., 2020.],
       [   0., 2019., 2018., 2017., 2016.]])
```

In [21]:
A = np.zeros((5,5))
A[3,1:] = [2023, 2022, 2021, 2020]
A[4,1:] = [2019, 2018, 2017, 2016]
print(A)

[[   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0. 2023. 2022. 2021. 2020.]
 [   0. 2019. 2018. 2017. 2016.]]


```
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 6.]])
```


In [22]:
import numpy as np

x=np.zeros((10, 10))
x[:5,9::-2]=np.identity(5)
x[5:,1::2]=np.diag((np.arange(2,7)))

print(x)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 6.]]
